name: Update contribution snake

on:
  schedule:
    - cron: "17 2 * * *"

  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - "assets/*.svg"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: mashood17
          outputs: |
            assets/github-contribution-snake.svg?palette=github-dark
            assets/github-contribution-snake-dark.svg?palette=github-dark&color_snake=#3fb950
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated animation
        uses: EndBug/add-and-commit@v9
        with:
          add: "assets/*.svg"
          message: "chore: update contribution animation"